### ISSUE TITLE
ZKS

### ISSUE THREAD

**Issue by farzin146** [farhan7reza7/Python-Greeting-Application#9]
# Issue Report

## Description

[Provide a brief description of the issue]

## Steps to Reproduce

[Outline the steps to reproduce the issue]

## Expected Behavior

[Describe what you expected to happen]

## Actual Behavior

[Describe what actually happened]

## Additional Information (if applicable)

[Include any additional information, logs, or screenshots]

**Comment by farhan7reza7** [comment]
> # Issue Report
> ## Description
> [Provide a brief description of the issue]
> 
> ## Steps to Reproduce
> [Outline the steps to reproduce the issue]
> 
> ## Expected Behavior
> [Describe what you expected to happen]
> 
> ## Actual Behavior
> [Describe what actually happened]
> 
> ## Additional Information (if applicable)
> [Include any additional information, logs, or screenshots]

It's just a template, not any issue...
